server:
  port: 4020
  error:
    include-message: always
    include-stacktrace: never
spring:
  #h2:
  #console:
  #enabled: true
  #path: /h2-console
  datasource:
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:file:~/data/nuevo;

    #username: sa
  #password: admin
    driver-class-name: org.postgresql.Driver
    dbCreate: update
  jpa:
    #database: h2
    database: postgresql
    hibernate:
      ddl-auto: update
    show_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    #atabase-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #dialect: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /swagger-ui
