server:
  port: 4020
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/prueba;
    dbCreate: update
    username: sa
    password: admin
    #driver-class-name: org.postgresql.Driver
    #url: postgres://twawllwlszdtpx:e4bce8bee34eeab2d4255825264dbecbfd54277a3b40a58375a62c29522dcc2a@ec2-44-209-24-62.compute-1.amazonaws.com:5432/ddev8llqvj6lrb
    #dbCreate: update
    #username: twawllwlszdtpx
    #password: e4bce8bee34eeab2d4255825264dbecbfd54277a3b40a58375a62c29522dcc2a
  jpa:
    database: h2
    #database: postgresql
    hibernate:
      ddl-auto: update
    show_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    #atabase-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        use_sql_comments: false
        format_sql: false
        #dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui